# Generated by Django 5.0.4 on 2024-06-08 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagePool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiClassTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_title', models.CharField(max_length=64, verbose_name='中文名')),
                ('english_title', models.CharField(max_length=64, verbose_name='英文名')),
            ],
        ),
        migrations.CreateModel(
            name='AiClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX1', models.FloatField(verbose_name='位置坐标，X1')),
                ('locationY1', models.FloatField(verbose_name='位置坐标，y1')),
                ('locationX2', models.FloatField(verbose_name='位置坐标，X2')),
                ('locationY2', models.FloatField(verbose_name='位置坐标，y2')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='图片创建时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagePool.sysimg', verbose_name='图片')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AiImageClass.aiclasstitle', verbose_name='标签')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
